// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crvwyhzphrlptumvjvkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNydnd5aHpwaHJscHR1bXZqdmtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NjY2ODksImV4cCI6MjA2NzM0MjY4OX0.SAO2oA7t5hmS-I6YpE5b2zglRyMFnSL5eD-1FFVZ990";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});